### ISSUE TITLE
exc_bad_access error

### ISSUE THREAD

**Issue by fdddf** [docee/PQActionSheet#1]
Using this lib. like this:
```objc
PQActionSheet *sheet = [[PQActionSheet alloc] initWithTitle:@"修改/添加头像" clickedAtIndex:^(NSInteger index) {
            
        } cancelButtonTitle:@"取消" otherButtonTitles:@"相册", @"拍照"];
[sheet show];
```
It breaks on line 109 
while ((curStr = va_arg(list, NSString *))) {

**Comment by docee** [comment]
请在otherButtonTitles后面加上nil，这是一个可变参数，如下：
PQActionSheet *sheet = [[PQActionSheet alloc] initWithTitle:@"修改/添加头像" clickedAtIndex:^(NSInteger index) {

        } cancelButtonTitle:@"取消" otherButtonTitles:@"相册", @"拍照",nil];
[sheet show];
